name: CI CD

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [ published ]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:

    - name: Code checkout
      uses: actions/checkout@v3

    - name: Setup terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.6.3"

    - name: Terraform format check
      run: |
        cd infra
        terraform fmt --check

  apply:
    name: Apply
    if: ${{ github.event_name == 'push' }}
    needs: validate
    runs-on: ubuntu-latest
    env:
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
    steps:

    - name: Code checkout
      uses: actions/checkout@v3

    - name: Setup terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.6.3"
        
    - name: Terraform init
      run: |
        cd infra
        terraform init

    - name: Terraform format check
      run: |
        cd infra
        terraform fmt --check

    - name: Terraform validate
      run: |
        cd infra
        terraform validate
      
    - name: Terraform apply
      run: |
        cd infra
        terraform apply \
          -auto-approve \
          -var="location=NorthEurope" \
          -var="storage_account_tier=Standard" \
          -var="storage_account_type=LRS"